spring.application.name=moviesapi
spring.config.import=file:./env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

api.docs.title=Movies API
api.docs.description=REST API for managing movies and exposing movie information.
api.docs.version=1.0.0
api.docs.contact.name=Enrique Sanchez
api.docs.contact.email=enrike.sanchez@tec.mx
api.docs.contact.url=https://github.com/enrikesancheztec/moviesapi

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

api.docs.title=Movies API
api.docs.description=REST API for managing movies and exposing movie information.
api.docs.version=1.0.0
api.docs.contact.name=Enrique Sanchez
api.docs.contact.email=enrike.sanchez@tec.mx
api.docs.contact.url=https://github.com/enrikesancheztec/moviesapi